In [2]:
#Implementar el pseudocódigo de la Figura 9.6, del método de eliminación de Gauss con pivoteo parcial
import math as mt
import numpy as np
tam=int(input("Digite el numero de ecuaciones:  "))
tam2=tam+1
matriz = np.array([[None] * (tam2) for i in range(tam)])
print "\nIngrese en orden las constantes de las ecuaciones..."
for e in range (tam):
    print "Ecuacion "+repr(e+1)+":"
    for f in range (tam2):
        a=float(input())
        matriz[e][f]=a
    print matriz[[e][0]:[e+1][0]],"\n"
vaux=[]
indicef=0
print "Matriz de coeficiente:\n",matriz
for k in range (tam-1):
    
    indicef=k
    for i in range (k+1,tam):
        if((abs(matriz[i][k]))>(abs(matriz[indicef][k]))):
            indicef=i
    
    if(k!=indicef):
        vaux[:]=matriz[k,:] #asigna matriz pivote menor 
        matriz[k,:]=matriz[indicef,:]#asigna matriz pivote mayor
        matriz[indicef,:]=vaux[:] #al que antes tenia el pivote mayor, la deja en la posicion que tenia el del pivote menor
    for i in range (k+1,tam):
        factor=matriz[i][k]/matriz[k][k]
        for j in range (k,tam2):
            matriz[i][j]=(matriz[i][j]-(factor*matriz[k][j]))
    """for i in range (j+1,tam):
        matriz[j,:]=(matriz[i,:]+matriz[j,:])*(-matriz[i][j]/matriz[j][j])"""
print "matriz triangular resultante:\n", matriz

ntam=tam-1
xn=(matriz[ntam][tam]/matriz[ntam][ntam])
x=[]
suma=0.0
for k in range (tam):
    x.append(0)
x[ntam]=xn
i=ntam-1
while(i>=0):
    suma=matriz[i][tam]
    j=i+1
    while(j<=ntam):
        suma=suma -matriz[i][j]*x[j]
        j=j+1
    x[i]=suma/matriz[i][i]
    i=i-1
for g in range(ntam+1):
    print "\nX"+repr(g+1)+"=",x[g]

Para este método el num de incognitas debe ser igual al numero de acuaciones.
Digite el numero de ecuaciones:  2

Ingrese en orden las constantes de las ecuaciones...
Ecuacion 1:
3
4
5
[[3.0 4.0 5.0]] 

Ecuacion 2:
6
7
8
[[6.0 7.0 8.0]] 

Matriz de coeficiente:
[[3.0 4.0 5.0]
 [6.0 7.0 8.0]]
matriz triangular resultante:
[[6.0 7.0 8.0]
 [0.0 0.5 1.0]]

X1= -1.0

X2= 2.0
